# Name of the GitHub Actions workflow
name: Build and Push Docker Image to GHCR

# Controls when the action will run
on:
  # Run the workflow on pushes to the 'main' branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Defines the job that will run
jobs:
  build-and-push-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant permissions for the GITHUB_TOKEN to write packages
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Log in to the GitHub Container Registry
      # This uses the built-in GITHUB_TOKEN for authentication, which is secure.
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Extract metadata (tags, labels) for the Docker image
      # This action automatically creates useful tags for your image, like 'latest'
      # and a tag based on the Git commit SHA for versioning.
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      # Step 4: Build the Docker image and push it to the GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
